In [27]:
import numpy as np
import pandas as pd
import re

In [110]:
file_path = 'final_perfume_data.csv'
df = pd.read_csv(file_path,  encoding = 'unicode_escape')

In [111]:
df.head(10)

Name                Brand  \
0                  Tihota Eau de Parfum               Indult   
1                           Sola Parfum               Di Ser   
2                        Kagiroi Parfum               Di Ser   
3          Velvet Fantasy Eau de Parfum              Montale   
4   A Blvd. Called Sunset Eau de Parfum        A Lab on Fire   
5  Freckled and Beautiful Eau de Parfum        A Lab on Fire   
6           Exit the King Eau de Parfum  Etat Libre d'Orange   
7                          Eshu Extrait                 PRIN   
8                    Saringkarn Extrait                 PRIN   
9                        Arsalan Parfum                 PRIN   

                                         Description  \
0   Rapa Nui for sugar, Tihota is, quite simply, ...   
1   A tribute to the expanse of space extending f...   
2   An aromatic ode to the ancient beauty of Japa...   
3   Velvet Fantasy is a solar fragrance where cit...   
4   There's no way A Lab On Fire could relocate t...   
5   There's no beauty quite like being young in t...   
6   In these tumultuous times, a fragrance that c...   
7   Eshu, the mischievous god of Yoruba legend, w...   
8   A taste of love and seduction. The value of l...   
9   The Persian legend of Arsalan is a story of a...   

                                               Notes  \
0                                Vanilla bean, musks   
1   Lavender, Yuzu, Lemongrass, Magnolia, Geraniu...   
2   Green yuzu, green shikuwasa, sansho seed, cor...   
3   tangerine,  pink pepper,  black coffee,  leat...   
4   Bergamot, almond, violet, jasmine, leather, s...   
5   Orange flower, neroli, honeysuckle, warm milk...   
6   Timur JE, Soap Foam Accord (Aldehydes & Musk)...   
7   Tobacco, hay, elemi, copaiba, olibanum, nutme...   
8   Saffron, champaca, fir balsam, beeswax, amber...   
9   Cambodian oud, Trat oud, jasmin sambac, champ...   

                                           Image URL  
0  https://static.luckyscent.com/images/products/...  
1  https://static.luckyscent.com/images/products/...  
2  https://static.luckyscent.com/images/products/...  
3  https://static.luckyscent.com/images/products/...  
4  https://static.luckyscent.com/images/products/...  
5  https://static.luckyscent.com/images/products/...  
6  https://static.luckyscent.com/images/products/...  
7  https://static.luckyscent.com/images/products/...  
8  https://static.luckyscent.com/images/products/...  
9  https://static.luckyscent.com/images/products/...

In [112]:

def normalize_text(text):
    text = re.sub(r'<.*?>', '', str(text))  
    text = text.encode("ascii", "ignore").decode() 
    text = re.sub(r'\s+', ' ', text) 
    return text.strip().lower()

df["Description"] = df["Description"].apply(normalize_text)
df["Notes"] = df["Notes"].apply(normalize_text)
df["final_description"] = (
    df["Description"].fillna('') + " " + df["Notes"].fillna('')
).str.strip()
df["final_description"] = df["final_description"].apply(normalize_text)
df = df.drop_duplicates(subset=["final_description"])

In [113]:
df = df[df["final_description"].str.strip() != ""]
df = df.drop_duplicates(subset=["final_description"])
df = df[df["final_description"].str.len() > 20] 

In [114]:
df.head(5)

Name          Brand  \
0                 Tihota Eau de Parfum         Indult   
1                          Sola Parfum         Di Ser   
2                       Kagiroi Parfum         Di Ser   
3         Velvet Fantasy Eau de Parfum        Montale   
4  A Blvd. Called Sunset Eau de Parfum  A Lab on Fire   

                                         Description  \
0  rapa nui for sugar, tihota is, quite simply, t...   
1  a tribute to the expanse of space extending fr...   
2  an aromatic ode to the ancient beauty of japan...   
3  velvet fantasy is a solar fragrance where citr...   
4  there's no way a lab on fire could relocate to...   

                                               Notes  \
0                                vanilla bean, musks   
1  lavender, yuzu, lemongrass, magnolia, geranium...   
2  green yuzu, green shikuwasa, sansho seed, cori...   
3  tangerine, pink pepper, black coffee, leather,...   
4  bergamot, almond, violet, jasmine, leather, sa...   

                                           Image URL  \
0  https://static.luckyscent.com/images/products/...   
1  https://static.luckyscent.com/images/products/...   
2  https://static.luckyscent.com/images/products/...   
3  https://static.luckyscent.com/images/products/...   
4  https://static.luckyscent.com/images/products/...   

                                   final_description  
0  rapa nui for sugar, tihota is, quite simply, t...  
1  a tribute to the expanse of space extending fr...  
2  an aromatic ode to the ancient beauty of japan...  
3  velvet fantasy is a solar fragrance where citr...  
4  there's no way a lab on fire could relocate to...

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df["final_description"])

In [116]:
print(tfidf_matrix)

  (0, 11231)	0.0705743645721091
  (0, 2199)	0.07147495260284811
  (0, 12129)	0.1546667518465119
  (0, 1723)	0.062228488414605584
  (0, 2801)	0.11441052799318846
  (0, 8251)	0.10914612199554155
  (0, 6496)	0.09482679268036139
  (0, 5137)	0.12350939946014307
  (0, 15481)	0.146817291388235
  (0, 1002)	0.146817291388235
  (0, 11574)	0.04852594296781133
  (0, 18852)	0.13041432373825962
  (0, 13843)	0.146817291388235
  (0, 6949)	0.09354990238884978
  (0, 7376)	0.08349669015732364
  (0, 6489)	0.08697733222208447
  (0, 11689)	0.14124801056207076
  (0, 12451)	0.06821055996544499
  (0, 10509)	0.09396624427404231
  (0, 5193)	0.08787792025282348
  (0, 9882)	0.03824632902653891
  (0, 15519)	0.07070048326901188
  (0, 18111)	0.12350939946014307
  (0, 6471)	0.09196868501172994
  (0, 12453)	0.07461343597184654
  :	:
  (2168, 7505)	0.06041662019135751
  (2168, 17539)	0.057058887678542086
  (2168, 13315)	0.1008537438155322
  (2168, 6261)	0.08126137919578855
  (2168, 15840)	0.054432599666937205
  (2168, 3

In [117]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [118]:
print(cosine_sim)

[[1.         0.01054009 0.00661755 ... 0.04739862 0.11061213 0.02217291]
 [0.01054009 1.         0.16274336 ... 0.01363452 0.00260447 0.00758203]
 [0.00661755 0.16274336 1.         ... 0.02546804 0.00780482 0.00789313]
 ...
 [0.04739862 0.01363452 0.02546804 ... 1.         0.02546129 0.01856729]
 [0.11061213 0.00260447 0.00780482 ... 0.02546129 1.         0.00775356]
 [0.02217291 0.00758203 0.00789313 ... 0.01856729 0.00775356 1.        ]]


In [119]:
import numpy as np

np.fill_diagonal(cosine_sim, 0)

n = cosine_sim.shape[0]
max_score = 0
best_pair = (None, None)


for i in range(n):
    for j in range(i + 1, n):
            if cosine_sim[i, j] > max_score and cosine_sim[i, j] < 0.9 and df.iloc[i]["Brand"].lower() != df.iloc[j]["Brand"].lower():
                max_score = cosine_sim[i, j]
                best_pair = (i, j)

i, j = best_pair

print("Cele mai asemănătoare două parfumuri sunt:")
print("Parfum 1:", df.iloc[i]["Name"])
print("Parfum 2:", df.iloc[j]["Name"])
print("Scor de similaritate:", cosine_sim[i, j])


with open("README.txt", "w", encoding="utf-8") as f:
    f.write("Cele mai asemănătoare două produse din brand-uri diferite identificate:\n")
    f.write(f"Produs 1: {df.iloc[i]['Name']}\n")
    f.write(f"Descriere 1: {df.iloc[i]['Description']}\n")
    f.write(f"Notes 1: {df.iloc[i]['Notes']}\n")
    f.write(f"Produs 2: {df.iloc[j]['Name']}\n")
    f.write(f"Descriere 2: {df.iloc[j]['Description']}\n")
    f.write(f"Notes 2: {df.iloc[j]['Notes']}\n")
    f.write(f"Scor de similaritate: {cosine_sim[i, j]:.4f}\n")

Cele mai asemănătoare două parfumuri sunt:
Parfum 1: Philosykos - Eau de Parfum
Parfum 2: Premier Figuier Eau de Toilette
Scor de similaritate: 0.49938080291052156
